//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationStudioAutomationPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationStudioAutomationPlugin.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Automation Sample.
        /// </summary>
        internal static string ActionCategory {
            get {
                return ResourceManager.GetString("ActionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo for working with documents.
        /// </summary>
        internal static string DocumentsViewPartDescription {
            get {
                return ResourceManager.GetString("DocumentsViewPartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo documents view.
        /// </summary>
        internal static string DocumentsViewPartTitle {
            get {
                return ResourceManager.GetString("DocumentsViewPartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin action executed.
        /// </summary>
        internal static string PluginActionExecutedMessage {
            get {
                return ResourceManager.GetString("PluginActionExecutedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action executed.
        /// </summary>
        internal static string PluginActionExecutedTitle {
            get {
                return ResourceManager.GetString("PluginActionExecutedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DemoAction.
        /// </summary>
        internal static string PluginActionName {
            get {
                return ResourceManager.GetString("PluginActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo action for sample app.
        /// </summary>
        internal static string PluginActionTooltip {
            get {
                return ResourceManager.GetString("PluginActionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample ribbon group.
        /// </summary>
        internal static string PluginRibbonGroup_Text {
            get {
                return ResourceManager.GetString("PluginRibbonGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo for implementing a view in Trados Studio.
        /// </summary>
        internal static string PluginViewDescription {
            get {
                return ResourceManager.GetString("PluginViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo plugin view.
        /// </summary>
        internal static string PluginViewName {
            get {
                return ResourceManager.GetString("PluginViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo for working with projects.
        /// </summary>
        internal static string ProjectsViewDescription {
            get {
                return ResourceManager.GetString("ProjectsViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo projects view.
        /// </summary>
        internal static string ProjectsViewTitle {
            get {
                return ResourceManager.GetString("ProjectsViewTitle", resourceCulture);
            }
        }
    }
}
