//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Sdk.FileTypeSupport.Samples.SimpleText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdl.Sdk.FileTypeSupport.Samples.SimpleText.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace selection with German quotes.
        /// </summary>
        internal static string DeQuot_Command_Description {
            get {
                return ResourceManager.GetString("DeQuot_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German quotes.
        /// </summary>
        internal static string DeQuot_Command_Name {
            get {
                return ResourceManager.GetString("DeQuot_Command_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First line of the file..
        /// </summary>
        internal static string Sniffer_Location {
            get {
                return ResourceManager.GetString("Sniffer_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First line of the file..
        /// </summary>
        internal static string Sniffer_Location1 {
            get {
                return ResourceManager.GetString("Sniffer_Location1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version header is missing..
        /// </summary>
        internal static string Sniffer_Message {
            get {
                return ResourceManager.GetString("Sniffer_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version header is missing..
        /// </summary>
        internal static string Sniffer_Message1 {
            get {
                return ResourceManager.GetString("Sniffer_Message1", resourceCulture);
            }
        }
    }
}
